name: CocoaPods
on:
  push:
    branches: 
      - '**'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  lint:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby 2.7.7
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.7'
          bundler-cache: true

      - run: bundle install

      - name: Select Xcode 15.1
        run: sudo xcode-select -s /Applications/Xcode_15.1.app/Contents/Developer

      - name: Cocoapods -> lint podspec and test
        run: bundle exec pod lib lint --verbose --platforms=ios


  deploy:
    needs: 
      - lint

    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')

    runs-on: macos-13

    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby 2.7.7
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.7'
          bundler-cache: true

      - run: bundle install

      - name: Select Xcode 15.1
        run: sudo xcode-select -s /Applications/Xcode_15.1.app/Contents/Developer

      - name: Publish Pod
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: bundle exec pod trunk push Endpoints.podspec
