name: Swift Package

on: [push]

jobs:
  build:

    runs-on: macos-13

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
