name: Code style check

on: [push]

jobs:
  check:

    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.4.0'
    - name: Check SwiftFromat
      run: swift run swiftformat . --lint

