name: Code style check

on: [push]

jobs:
  check:

    runs-on: macos-13

    steps:
    - uses: actions/checkout@v4
    - name: Select Xcode 15.1
      run: sudo xcode-select -s /Applications/Xcode_15.1.app/Contents/Developer
    - name: Check SwiftFromat
      run: swift run swiftformat . --lint

